### ISSUE TITLE
Typeface is different

### ISSUE THREAD

**Issue by Kamil1982** [therealklanni/badger#14]
Entering the "Codename" the Typeface is different to the rest of the card!

**Comment by therealklanni** [comment]
Please provide additional information:
- Operating System & version
- Browser & version
- Screenshot

**Comment by Kamil1982** [comment]
Win XP SP3
Firefox 22.0
Google Chrome Version 28.0.1500.72 m

2013/7/24 Kevin Lanni notifications@github.com

**Comment by therealklanni** [comment]
In order to see the issue, you will need to provide me a screenshot.

**Comment by Kamil1982** [comment]
I did that in the first place but it seems not to provide the images to
this address from github.
You may have another emailaccount I can send them?

2013/7/25 Kevin Lanni notifications@github.com

**Comment by therealklanni** [comment]
You can't attach images to email to GitHub. You have to log in to GitHub and use the UI to attach an image to an issue.

**Comment by therealklanni** [comment]
Unable to reproduce.
