### ISSUE TITLE
Broken in app directory

### ISSUE THREAD

**Issue by stillru** [therealklanni/badger#2]
# bug

**Comment by therealklanni** [comment]
Can you please elaborate?

If you are trying to publish your own copy of Badger from the `app/` subdirectory, it won't work. You have to do a build and then publish the files from the `dist/` subdirectory.

I am working on instructions for this.

**Comment by stillru** [comment]
OK. I will wate for instruction :+1: :-)

**Comment by therealklanni** [comment]
Check [here](http://github.com/therealklanni/badger#community-customization) for instructions
