### ISSUE TITLE
Testing Develop Branch

### ISSUE THREAD

**Issue by mattdbr** [therealklanni/badger#23]
Is there a way to test the develop branch without cloning to your own computer?

**Comment by therealklanni** [comment]
No, but I've been considering that. I might be able to set up something.

**Comment by stillru** [comment]
Hmmm... how to setup build env?

**Comment by therealklanni** [comment]
Oh, it's simple, just run the following commands in the directory you've cloned into:

```
npm install
bower install
```

Work in the `app` directory. The `dist` directory is built automatically (which I do when I merge into master, so you won't have to worry about that) by Grunt and should not be directly modified.

Run `grunt server` to test your code.

Side note: please remember to submit pull requests to `develop`

**Comment by stillru** [comment]
> Package: npm
> Version: 1.1.4~dfsg-1
> ii  nodejs            0.6.12~dfsg1-1ubuntu1
> ii  nodejs-dev        0.6.12~dfsg1-1ubuntu1

Please update npm, nodejs packages, and try again.
 npm should work but it's possible the failing installation
 is for a module supporting only nodejs >= 0.8.

**Comment by therealklanni** [comment]
Looks like you have nodejs 0.6.12, install the latest nodejs from the nodejs site (the Ubuntu apt repository doesn't seem to have the latest).
