### ISSUE TITLE
URL text not updating when editing on card

### ISSUE THREAD

**Issue by mattdbr** [therealklanni/badger#32]
I know this is an ongoing issue but here's another instance. 

When typing directly onto the card the text updates in the field but not on the card. Only when the field is clicked on is the text updated. 

See pic below

![clipboard01](https://f.cloud.github.com/assets/2032746/1250929/7f6c4070-2b0d-11e3-8a15-5a31727f7294.jpg)

**Comment by therealklanni** [comment]
So when typing in the text field on the image it only updates when the user clicks onto the text field on the right?

**Comment by mattdbr** [comment]
That'd be right

**Comment by therealklanni** [comment]
Please test.

**Comment by mattdbr** [comment]
My initial tests look promising.
