### ISSUE TITLE
Replace GitHub buttons with something better

### ISSUE THREAD

**Issue by therealklanni** [therealklanni/badger#33]
This plugin never worked as intended. We're better off with static GitHub images, but another plugin that provides some additional features (such as star/fork/watch counts) would also be nice.

**Comment by mattdbr** [comment]
Shouldn't take too long but I've got exams until 5th November.

**Comment by mattdbr** [comment]
Fixed for some more counts. Will have a hunt tomorrow for watch counters. It's very late at the moment.

**Comment by mattdbr** [comment]
Is this ready for closure? I've had a look but there aren't that many options for buttons. Adding counts I did in the above merge.
