### ISSUE TITLE
Allow levels more than 8

### ISSUE THREAD

**Issue by 537719** [therealklanni/badger#38]
Many Ingress players have 2 3 or even 4 more AP than required to reach level 8 : allow them to show this on the badge, showing a 9 or more as level number.

**Comment by therealklanni** [comment]
How about utilizing some empty space for AP count instead? I'm not sure I like the idea of increasing the level cap (since that's not an official thing in-game at this time) on the badge.

Thoughts?

**Comment by mattdbr** [comment]
Apparently within the next few months they'll be adding it so we should prepare for it. 

Total AP count IMO is too variable and would have to be changed frequently (unless you left a space to be written on with whiteboard marker)

**Comment by therealklanni** [comment]
Let's go ahead and implement this on a new branch ("additional-levels" ?) and wait to merge it in when it's officially a feature of Ingress, that way we can grab the correct (official) level colors to finish the implementation before merging it into production.

Reasoning being, we don't know for certain how many additional levels will be added.

Additionally, we could implement a complimentary feature to this which allows the user to go into an "advanced options" to modify the badge in non-standard ways (i.e. select a non-standard level number, change text in other areas when that's implemented, etc). 

We will also need to consider the case of 2-digit level numbers, as this was never accounted for and could cause some style issues.

**Comment by therealklanni** [comment]
Currently working on an implementation to allow higher levels or custom level color to be chosen (enable with checkbox).

**Comment by therealklanni** [comment]
Complete and merged in master.
