### ISSUE TITLE
Show bigger result image

### ISSUE THREAD

**Issue by 537719** [therealklanni/badger#39]
The result image is too small to be smartly printed (188 x 302)

**Comment by therealklanni** [comment]
If this is a bug, please provide more information (browser, version, operating system, etc). The size of the badge was tailored specifically to fit in a 57mm x 95mm lamination pouch, and prints fine in most browsers (there is an open bug for Firefox/Safari: #8).

**Comment by therealklanni** [comment]
Marking as duplicate until more information is provided.
