### ISSUE TITLE
The ability to add your inviter's name

### ISSUE THREAD

**Issue by thayol** [therealklanni/badger#41]
Your inviter's name should be on the back of the card, positioned at the top of the back side.

EDIT: Fixed old broken English.

**Comment by therealklanni** [comment]
Please explain. I don't know what a Master/Invitator is.

**Comment by stillru** [comment]
I think - its about nickname of hilevel player who invite person in game.

**Comment by stillru** [comment]
In our community - Jedi and padavan

**Comment by mattdbr** [comment]
@therealklanni This shouldn't be too hard to add as an option
@stillru Whereabouts would you think would be a good place to put it.

**Comment by therealklanni** [comment]
This could be implemented as part of the custom subtext (the part that currently says "OYM-042 Operation Level") or perhaps custom text in place of "Member"

**Comment by thayol** [comment]
Closing after 7 years of inactivity.
