### ISSUE TITLE
Resistance faction is not switching

### ISSUE THREAD

**Issue by DJ-R3m** [therealklanni/badger#5]
When I choose Resistance faction there's no changes. Badge still green Enlightened

**Comment by therealklanni** [comment]
Please provide more information:
- Operating System & Version
- Browser & Version

**Comment by louisrousseau** [comment]
I can confirm this occurs with both Pale Moon 64 bits (let's say Firefox for our purposes) and IE 9, running on Windows 7.

**Comment by DJ-R3m** [comment]
Firefox 22.0 Ubuntu 13.04 amd64

**Comment by kuoirad** [comment]
Firefox 22 on OS X 10.8.4.  Works correctly on Safari.
