### ISSUE TITLE
Levels only get up to 8 :(

### ISSUE THREAD

**Issue by MTRNord** [therealklanni/badger#53]

**Comment by therealklanni** [comment]
Correct. This project was created back when there were only 8 levels. I don't plan on updating it. 

However, you're welcome to fork and add the functionality yourself. I'll even happily accept a PR if you want to contribute back to the project.

**Comment by MTRNord** [comment]
Ok will do so :) looks pretty straightforward to do. Maybe i will also pr some other issues requests

**Comment by therealklanni** [comment]
That would be awesome!
