### ISSUE TITLE
Codename input overflows

### ISSUE THREAD

**Issue by UndergroundWire** [therealklanni/badger#7]
I love this project but I have an issue with how it displays my Agent ID (Und3rgr0undW1r3). Too long of a name and it looks horrible. Text should be dynamically sized. So as the number of characters increase, the font decreases gradually.

**Comment by therealklanni** [comment]
Going to split this into 2 issues:
1. bug to fix the overflow
2. enhancement to add dynamic font sizing

A clever user could open the Chrome Dev Tools and tweak the CSS live to get the desired results in the meantime.

**Comment by UndergroundWire** [comment]
That is 100% correct and exactly what I did to make my badge. Unfortunately
not everyone knows CSS and HTML.

Thanks for your work.
